import type { Metadata } from 'next';
import { Noto_Sans, Instrument_Serif, Oswald } from 'next/font/google';
import '@/styles/globals.css';
import { cn } from '../src/lib/utils';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/provider/theme-provider';
import AuthWrapper from '@/features/auth/components/AuthWrapper';
import { Suspense } from 'react';
import Loading from '@/components/layout/loading';

const instrumentSerif = Instrument_Serif({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-instrument',
});
const notoSans = Oswald({ subsets: ['latin'], variable: '--font-noto' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        notoSans.variable,
        instrumentSerif.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense fallback={<Loading />}>
            <AuthWrapper>{children}</AuthWrapper>
          </Suspense>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
